# Generated by Django 4.2.7 on 2023-12-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("OmniApp", "0002_alter_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="otp_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="otp_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="otp_secret_key",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
