# Generated by Django 4.2.7 on 2023-12-25 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("OmniApp", "0005_alter_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
    ]
