# Generated by Django 4.2.7 on 2023-12-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("OmniApp", "0009_remove_customer_user_alter_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.UUIDField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
