# Generated by Django 4.2.7 on 2023-12-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("OmniApp", "0011_alter_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
