# Generated by Django 4.2.7 on 2023-12-27 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("OmniApp", "0014_alter_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="otp_email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="otp_email_verified",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="otp_secret_key",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
    ]
