# Generated by Django 4.2.7 on 2024-01-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("OmniApp", "0017_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image_1",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image_2",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image_3",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_short_description",
            field=models.CharField(default="", max_length=40),
        ),
    ]
