# Generated by Django 4.2.7 on 2024-01-22 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("OmniApp", "0022_alter_product_product_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_quantity", models.PositiveIntegerField(default=0)),
                (
                    "c_user",
                    models.ForeignKey(
                        default="550e8400-e29b-41d4-a716-446655440000",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_cart",
                        to="OmniApp.customer",
                    ),
                ),
                (
                    "c_username",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usernmae_cart",
                        to="OmniApp.customer",
                        to_field="username",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="OmniApp.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OmniApp.product",
                    ),
                ),
            ],
        ),
    ]
