# Generated by Django 4.2.7 on 2024-01-22 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("OmniApp", "0023_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="c_user",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="c_username",
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                default="23122",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
