# Generated by Django 4.2.7 on 2024-01-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("OmniApp", "0028_mainadmin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="category_images/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="MainAdmin",
        ),
    ]
