# Generated by Django 4.2.7 on 2024-01-28 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("OmniApp", "0030_tag_product_categories_product_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Categoryies",
        ),
    ]
