# Generated by Django 4.2.7 on 2024-02-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("OmniApp", "0031_rename_category_categoryies"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="company_logo_image",
            field=models.ImageField(blank=True, null=True, upload_to="logo_images/"),
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
